version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 80:80
  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:latest
  #   ports:
  #     - 8978:8978
  # adminer:
  #   image: adminer:latest
  #   ports:
  #     - 8080:8080
